config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "profile", to: "pages#profile"

  resources :paints do
    resources :bookings, only: [:new, :create, :edit, :destroy]
  end
   resources :bookings, only: [:index, :show]
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  #get "booking_confirmation", to: "pages#confirmation"

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :paint
  validates :user, presence: true
  validates :paint, presence: true
  validates :date, presence: true
end

app/models/paint.rb
class Paint < ApplicationRecord
  geocoded_by :address
  belongs_to :user
  validates :brand, presence: true
  validates :colour, presence: true
  validates :volume, presence: true
  has_one_attached :photo
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  add_flash_types :danger, :info, :warning, :success, :messages
end

def default_url_options
  { host: ENV["www.ourpaint.xyz"] || "localhost:3000" }
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @booking = Booking.all
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @booking = Booking.new
    @paint = Paint.find(params[:paint_id])
  end

  def create
    @booking = Booking.new(booking_params)
    @paint = Paint.find(params[:paint_id])
    @booking.paint = @paint
    @booking.user = current_user
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render "new"
    end
  end


  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
  end

  private

  def booking_params
    params.require(:booking).permit(:date, :paint_id, :user_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end

  def profile
    @bookings = Booking.where(user: current_user)
  end
end

app/controllers/paints_controller.rb
class PaintsController < ApplicationController
  before_action :find_paint, only: [:update, :show, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show, :new, :create]

  def index
    postcode = params[:postcode]

    @paints = Paint.near(postcode, 10)

     @markers = @paints.geocoded.map do |paint|
      {
        lat: paint.latitude,
        lng: paint.longitude,
        info_window: render_to_string(partial: "info_window", locals: { paint: paint }),
        image_url: helpers.asset_url('paint_marker.svg')
      }
    end
  end

  def show
    @paint = Paint.find(params[:id])
    @booking = Booking.new

    @markers =[
      {
        lat: @paint.latitude,
        lng: @paint.longitude,
        info_window: render_to_string(partial: "info_window", locals: { paint: @paint }),
        image_url: helpers.asset_url('paint_marker.svg')
      }]
  end

  def new
    @paint = Paint.new
  end

  def create
    @paint = Paint.new(paint_params)
    @paint.user = current_user
    if @paint.save

      flash[:notice] = "Thanks for recycling your paint and saving the planet!"


      redirect_to paint_path(@paint)


    else
      render :new
    end
  end

  def edit
    @paint = Paint.find(params[:id])
  end

  def update
    @paint = Paint.find(params[:id])
    @paint.update(paint_params)
    #@paint.user = current_user
    redirect_to paint_path(@paint)
  end

  def destroy
    @paint = Paint.find(params[:id])
    @paint.destroy
  end

  private

  def find_paint
    @paint = Paint.find(params[:id])
  end

  def paint_params
    params.require(:paint).permit(:brand, :colour, :volume, :photo, :address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/bookings/_flash.html.erb
<% if flash.any? %>
<% flash.each do |type, msg| %>
<div>
<%= msg %>
</div>
<% end %>
<% end %>

app/views/bookings/_form.html.erb
  <div class="form-wrapper card-map-2" style="width: 400px; margin: 0 auto;">
    <%# <h2>Book your paint collection</h2> %>
      <div class="container">
        <%= simple_form_for ([@paint, @booking]) do |f| %>
        <%= f.input :date, as: :string, required: false, input_html: {class: "datepicker"} %>
          <div>
            <%= f.submit "Book your collection",  class: "btn-black mb-3"  %>
          </div>
        <% end %>
      </div>
  </div>

app/views/bookings/new.html.erb
<div class="banner-bookings">
  <div><h1 class="show-title-h2 top-align">Pick a date and time</h1></div>
   <div class="paint-details-bookingform">
      <div class="card-show">
        <div class="card-image"><%= cl_image_tag(@paint.photo.key, width: 300, height: 300, crop: :fill) %></div>
        <div class="card-text">
          <h1><%= @paint.brand %></h1>
          <p><%= @paint.colour %></p>
          <p><%= @paint.volume %></p>
        </div>
        <div class="container-bookings">
          <%= render "form", booking: @booking %>
        </div>
     </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="login-wrapper">
  <div><h1 class="show-title-h2 top-align">Booking confirmed</h1></div>
  <div class="aboutus-container">
    <div class="profile-box">
      <h1 class="profile-box-h1">Anna</h1>
      <%= image_tag "happy-painter-profile.jpg", style: "width: 150px"%>
      <%= cl_image_tag(@booking.paint.photo.key, height: 150, width: 150, crop: :fill) %>
          <div class="booking-paint-info">
            <p class="booking-paint-info-details"><%= @booking.paint.colour%></p>
            <p class="booking-paint-info-details"><%= @booking.paint.volume%></p>
            <p class="booking-paint-info-details"><%= @booking.paint.address%></p>
            <p class="booking-paint-info-details">contact number: 07974389972</p>
            <p class="booking-paint-info-details">pick up details: ring the top buzzer</p>
          </div>
    </div>
  </div>


  <div><h1 class="show-title-h2 top-align">Badges Earned</h1></div>


  <%# <div class="d-flex justify-content-center align-items-center px-4 mx-5"> %>

    <div class="badges-container">
      <div class="badges-card">
        <div class="box">
          <div class="badge-content">
            <h3>Your first booking</h3>
            <h4>Nice one, you booked your first paint collection</h4>
            <p><%= image_tag "trophy.png", class: "d-block mb-3 badge", style: "width: 200px" %></p>
          </div>
        </div>
      </div>

      <div class="badges-card">
        <div class="box">
          <div class="badge-content">
            <h3>Paint superhero</h3>
            <h4>Doing your bit to keep paint out of landfill</h4>
            <p><%= image_tag "dog.png", class: "d-block mb-3 badge", style: "width: 200px" %></p>
          </div>
        </div>
      </div>

      <div class="badges-card">
        <div class="box">
          <div class="badge-content">
            <h3>OurPaint family</h3>
            <h4>You're one of us now! Never buy new paint again</h4>
            <p><%= image_tag "teamwork.png", class: "d-block mb-3 badge", style: "width: 200px" %></p>
          </div>
        </div>
      </div>
    </div>

      </div>
      </div>
  <%# </div> %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title><%= meta_title %></title>
<meta name="description" content="<%= meta_description %>">

            <!-- Facebook Open Graph data -->
            <meta property="og:title" content="<%= meta_title %>" />
            <meta property="og:type" content="website" />
            <meta property="og:url" content="<%= request.original_url %>" />
            <meta property="og:image" content="<%= meta_image %>" />
            <meta property="og:description" content="<%= meta_description %>" />
            <meta property="og:site_name" content="<%= meta_title %>" />

            <!-- Twitter Card data -->
            <meta name="twitter:card" content="summary_large_image">
            <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
            <meta name="twitter:title" content="<%= meta_title %>">
            <meta name="twitter:description" content="<%= meta_description %>">
            <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
            <meta name="twitter:image:src" content="<%= meta_image %>">

            <link href="/assets/favicon (1).ico" rel="shortcut icon" type="image/x-icon" />

    <title>OurPaint</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
 <div class="d-flex flex-column min-vh-100">
      <%= render 'shared/navbar' %>
      <%= render 'shared/flashes' %>
      <article class="flex-grow-1 body-container">
        <%= yield %>
      </article>
      <%= render 'shared/footer' %>
    </div>
  </body>

</html>

app/views/pages/home.html.erb
<% content_for(:navbar_class, "navbar-home") %>

<div class="banner">
  <div class="banner-content">
    <h1>Our Paint</h1>
    <center><p>Find second-hand paint in your neighbourhood</p></center>

    <div class="input-group mb-3 search-bar">
      <form action="/paints" class="search-form">
          <input type="text" id="postcode" class="form-control" name="postcode" placeholder="Enter Postcode">
          <input class="input-group-text" type="submit" value="Search">
      </form>
    </div>
  </div>
</div>

<div class="aboutus-container text-center mb-5">
  <div class="text-col">
    <h2 class="home-about-h2 mb-5">Our Mission</h2>
    <h3>OurPaint was launched to help stop excess paint going to landfills across the UK.</h3>
    <br>
    <h3>Central to this is our desire to create sharing micro-communities in neighbourhoods across the country.</h3>
    <br>
    <h3>We believe that these communities hold the key to keeping hazardous chemicals out of landfill, and keeping more money in people's wallets.</h3>
    <br>
  </div>
  </div>
</div>

<div class="aboutus-container-2 mt-5">
  <h2 class="home-about-h2 text-center mb-5">Paint facts</h2>

  <div class="d-flex justify-content-center mb-5">

    <div class="d-flex flex-column justify-content-center align-items-center px-4 mr-4">
      <%= image_tag "wallet.png", class: "d-block mb-3", style: "width: 200px" %>
      <p class="text-center mb-0">In 2020, the UK bought nearly £16 million litres of paint.</p>
      <p class="text-center">This is <strong>bad</strong> for your wallet.</p>
    </div>

    <div class="d-flex flex-column justify-content-center align-items-center px-4 mx-5">
      <%= image_tag "rubbish.png", class: "d-block mb-3", style: "width: 200px" %>
      <p class="text-center mb-0">Approx 50 million litres of paint goes to landfill in the UK each year.</p>
      <p class="text-center">This is <strong>bad</strong> for the environment.</p>
    </div>

    <div class="d-flex flex-column justify-content-center align-items-center px-4">
      <%= image_tag "paint.png", class: "d-block mb-3", style: "width: 200px" %>
      <p class="text-center">Only <strong>2%</strong> of leftover paint is recycled today.</p>
    </div>

  </div>
</div>

<section>
  <div class="container">
    <div><h1 class="carousel-h1">Our Community</h1></div>
    <div class="carousel-container carousel-small">
    <div class="card-container">
          <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">

            <%= image_tag "matthew_pic.jpg", class: "d-block w-100" %>

          </div>
          <div class="carousel-item">
            <%= image_tag "lorraine_pic.jpg", class: "d-block w-100" %>
          </div>
          <div class="carousel-item">
            <%= image_tag "pexels-cottonbro.jpg", class: "d-block w-100" %>
          </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>

    </div>
  </div>
</section>
<br>
<br>
  </div>
</div>

app/views/pages/profile.html.erb
<div class="login-wrapper">
  <h1 style="font-family:Permanent Marker; font-size: 100px;text-align:center">Your Paint Bookings</h1>
  <div class="login-wrapper-profile">
  <% if @bookings %>
    <% @bookings.each do |booking| %>
      <div class="card" style="width: 18rem;">
        <div class="card-body">
          <h4 class="card-title">Paint Details</h4>
          <div class='d-flex align-items-center'>
            <%= cl_image_tag(booking.paint.photo.key, height: 85, width: 85, crop: :fill) %>
            <div class="ml-3">
              <p><%= booking.paint.colour%></p>
              <p><%= booking.paint.brand %></p>
            </div>
          </div>
          <%= link_to "Relist Paint", edit_paint_path(booking.paint), class: "btn btn-success profile-card-btn" %>
        </div>
      </div>
      <% end %>
    <% end %>
  </div>

</div>

app/views/paints/_form.html.erb
<%= render "bookings/flash" %>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-sm-3">

<%= simple_form_for [ @paint ] do |f| %>
  <%= f.input :brand, default: 'Pick from the dropdown list', collection: ['Pick from the list below', 'Abigail Ahern', 'Annie Sloan', 'Auro', 'Bedec', 'Blackfriar', 'Chiselwood', 'Craig & Rose', 'Crown', 'Designers Guild', 'Dulux', 'EarthBorn',
  'Ecos', 'Farrow & Ball', 'Fired Earth', 'Francescas Lime Wash', 'Johnstones', 'Laura Ashley', 'The Little Greene Paint Company', 'Nutshell Natural Paints', 'Paint by Conran', 'Paint & Paper Library', 'Rose of Jericho', 'Sanderson', 'Siecle', 'Zoffany'] %>
  <%= f.input :colour, placeholder: 'E.g. ...Twilight Dawn' %>
  <%= f.input :volume, placeholder: 'E.g. ...0.75l, 1.5' %>
  <%= f.input :address, placeholder: 'E.g. ...5 Jarvis Road, London' %>
  <%#= f.input :address, placeholder: 'Enter your address here' %>
  <br>
  <%= f.label :photo, class: 'block' %>
  <%= f.input_field :photo, as: :file,  class: 'photo-button' %>
  <br>
  <br>
  <%= f.submit "List Your Paint", class: "btn-black" %>
  <br>
  <br>
<% end %>

    </div>
  </div>
</div>

app/views/paints/_info_window.html.erb
<div>
        <%= link_to paint_path(paint) do  %>
          <div>
            <h6 class="popup-content"><%= paint.brand %></h6>
            <h6 class="popup-content"><%= paint.colour %></h6>
            <h6 class="popup-content"><%= paint.volume %></h6>
           </div>
           <% end %>
          </div>
</div>

app/views/paints/edit.html.erb
<div class="login-wrapper">



<%= render "form", paint: @paint %>

<%= render 'shared/footer_relative' %>

</div>

app/views/paints/index.html.erb
  <div class="paint-index-page">
    <div class="container-wide">

      <div class="content">
          <div class="cards">
            <% @paints.each do | paint | %>
              <div>
              <%= link_to paint_path(paint) do  %>
                <div class="card-horizontal">
                <div>
                 <h6 class="card-horizontal-brand"><%= paint.brand %></h6>
                  <h4 class="card-horizontal-content"><%= paint.colour %></h4>
                </div>

                <%= cl_image_tag(paint.photo.key, height: 75, width: 75, crop: :fill) %>

                </div>
                <% end %>
              </div>
            <% end %>
          </div>

        <div id="map"
          style="width: 100%; height: 675px; border-radius: 5px"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>

      </div>
    </div>

  </div>

app/views/paints/new.html.erb
<div class="login-wrapper">
  <div>

    <h1 class="home-about-h2">List your used paint</h1>


    <div class="container paint-new">

        <div class="paint-new-form">
          <%= render "form", paint: @paint %>
        </div>
      <div class="link-paint-new">
        <%= link_to "Go back", paints_path, class: "btn-black" %>
      </div>
    </div>
  </div>
  <br>
  <br>
  <br>
  <br>

</div>

app/views/paints/show.html.erb
<div class="banner-show">
<div><h1 class="show-title-h2 top-align">Paint details</h1></div>
<div class="card-map">
    <div class="card-show">
      <div class="card-image"><%= cl_image_tag(@paint.photo.key, height: 300, width: 300, crop: :fill) %></div>
      <div class="card-text">
        <h1><%= @paint.brand %></h1>
        <p><%= @paint.colour %></p>
        <p><%= @paint.address %></p>
        <p><%= @paint.volume %></p>
        <%= link_to "Book this paint!", new_paint_booking_path(@paint), class: "btn-black" %>
      </div>
    </div>
    <div class="map-show">
      <div id="map"
     style="width: 100%; height: 100%; border-radius: 5px"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
    </div>

</div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div>
    <h2 class="footer-h2">Our Paint</h2>
  </div>
  <div class="footer-copyright">
    © OurPaint-2022
  </div>
</div>

app/views/shared/_footer_relative.html.erb
<div class="footer-relative">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div>
    <h2 class="footer-h2">Our Paint</h2>
  </div>
  <div class="footer-copyright">
    © OurPaint-2022
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon <%= yield (:navbar_class) %>">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "paint.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>

          <li class="nav-item btn-nav">
            <%= link_to "List your old paint", new_paint_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/matthewg543", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false%>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "My profile", profile_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <!--li class="nav-item"-->
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          <!--/li-->
        <% end %>
      </ul>
    </div>
  </div>
</div>